# Test Makefile with nested variables

# should fail if actually executed
CC = no-gcc
CFLAGS = -Wall -O2
COMPILE = $(CC) $(CFLAGS)
CMD = $(COMPILE) -c

all: test.o

test.o: Makefile.nested-dry
	$(CMD) $<

clean:
	rm -f *.o
