# Sub-makefile for nested make -f test

.PHONY: all target1 target2

all: target1 target2
	@echo "Sub-makefile all done"

target1:
	@echo "Building target1 from sub-makefile"
	touch nested-f-target1.txt

target2:
	@echo "Building target2 from sub-makefile"
	touch nested-f-target2.txt
