#!/bin/bash
# Smak - Makefile parser and build tool
# Bash wrapper scrip

script=$(basename $0)
exe=$0
link=$(readlink $exe)

SCRIPT_DIR="$(dirname $exe)"

# Find the directory where this script is located
while [ ! -z "$link" ]  ; do
    exe=$link
    case $exe in
	*/*) SCRIPT_DIR="$(dirname $exe)" ;;
    esac
    link=$(readlink $exe)
    if [ -z "$link" ] ; then
	break
    fi
done

while true ; do
    case $1 in
      	-KE) shift ; source $1 ; shift ;;
	*)   break ;;
    esac
done

if [ ${PATH/:*/} != "$PWD" ] ; then
    PATH=${PWD}:${PATH}
fi

# Pass the invocation name to smak.pl via environment variable
# Use basename so $(MAKE) is set to "smak" not the full path
export SMAK_INVOKED_AS="$0"

# Set launcher path for bug reports
export SMAK_LAUNCHER="$SCRIPT_DIR/$script"

export PERLLIB="$SCRIPT_DIR"

# Execute the Perl script with all arguments passed through
exec perl ${SMAK_PERL_DEBUG} "$SCRIPT_DIR/$script.pl" "$@"
