Warning: Could not parse sub-makefile 'CMakeFiles/Makefile2': Cannot open CMakeFiles/Makefile2: No such file or directory at /home/user/smak/Smak.pm line 1259.

/usr/bin/cmake -S/mnt/y/Xyce-8/xyce -B/mnt/y/Xyce-8/xyce-build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /mnt/y/Xyce-8/xyce-build/CMakeFiles /mnt/y/Xyce-8/xyce-build//CMakeFiles/progress.marks
../../smak  -f CMakeFiles/Makefile2 all
/usr/bin/cmake -E cmake_progress_start /mnt/y/Xyce-8/xyce-build/CMakeFiles 0
